apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ldapmon.configmapName" . }}
  labels:
    {{- include "ldapmon.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Files.Get "config.yaml" | nindent 4 }}
