apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ldapmon.fullname" . }}
  labels:
    {{- include "ldapmon.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ldapmon.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ldapmon.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "ldapmon.serviceAccountName" . }}
      volumes:
        - name: config
          configMap:
            name: {{ include "ldapmon.configmapName" . }}
      containers:
        - name: ldapmon
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["--config", "/app/config/config.yaml"]
          env:
            - name: RUST_LOG
              value: {{ .Values.env.RUST_LOG | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /app/config
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
